### ISSUE TITLE
unpack failed

### ISSUE THREAD

**Issue by Perfect-Web** [easy-swoole/kafka#22]
```Fatal error: Uncaught EasySwoole\Kafka\Exception\Exception: unpack failed. string(raw) length is 0 , TO s in /var/www/vendor/easyswoole/kafka/src/Protocol/Protocol.php:260
Stack trace:
#0 /var/www/vendor/easyswoole/kafka/src/Protocol/Protocol.php(185): EasySwoole\Kafka\Protocol\Protocol::checkLen('s', '')
#1 /var/www/vendor/easyswoole/kafka/src/Protocol/GroupCoordinator.php(43): EasySwoole\Kafka\Protocol\Protocol::unpack('s', '')
#2 /var/www/vendor/easyswoole/kafka/src/Protocol.php(282): EasySwoole\Kafka\Protocol\GroupCoordinator->decode('')
#3 /var/www/vendor/easyswoole/kafka/src/Group/Process.php(52): EasySwoole\Kafka\Protocol::decode(10, '')
#4 /var/www/vendor/easyswoole/kafka/src/Consumer/Process.php(143): EasySwoole\Kafka\Group\Process->getGroupBrokerId()
#5 /var/www/vendor/easyswoole/kafka/src/Consumer/Process.php(96): EasySwoole\Kafka\Consumer\Process->getGroupNodeId()
#6 /var/www/vendor/easyswoole/kafka/src/Consumer.php(38): EasySwoole\Kafka\Consumer\Process->subscribe(Object(Closure), 0.01, 128)
#7 /var/www/src/V in /var/www/vendor/easyswoole/kafka/src/Protocol/Protocol.php on line 260```

**Comment by leocavalcante** [comment]
I get this when my VPN drops and I can't reach the brokers anymore. Maybe gives you some tips.
